---
swagger: 2.0
info:
  title: ImageManager1Api
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::AWSRegion}:${AWS::AccountId}:function:${ResizeFunction.Arn}/invocations
        type: AWS_PROXY
        httpMethod: post
