AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  EdgeLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

  ViewerRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist/viewer-request-function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 1
      Role: !GetAtt EdgeLambdaRole.Arn

  OriginRequestFunction:
   Type: AWS::Serverless::Function
   Properties:
     CodeUri: ../dist/origin-request-function.zip
     Handler: index.handler
     Runtime: nodejs6.10
     MemorySize: 128
     Timeout: 3
     Role: !GetAtt EdgeLambdaRole.Arn

Outputs:
  OriginRequestFunctionArn:
    Value: !GetAtt OriginRequestFunction.Arn
  ViewerRequestFunctionArn:
    Value: !GetAtt ViewerRequestFunction.Arn
  RoleArn:
    Value: !GetAtt EdgeLambdaRole.Arn
