AWSTemplateFormatVersion: 2010-09-09
Outputs:
  ViewerRequestFunctionArn:
    Value:
      Fn::GetAtt:
      - ViewerRequestFunction
      - Arn
Resources:
  ViewerRequestFunction:
    Properties:
      CodeUri: s3://temp-code-imageresize-74d0c5dff93ef717/f92a2f236db928a78768777da091aa45
      FunctionName:
        Fn::Sub: test-${AWS::Region}${AWS::AccountId}-ViewerRequestFunction
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs6.10
      Timeout: 1
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
