AWSTemplateFormatVersion: 2010-09-09
Outputs:
  BucketWebsiteUrl:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-BucketWebsiteUrl
    Value:
      Fn::GetAtt:
      - IMAGEBUCKET
      - WebsiteURL
  ImageBucket:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ImageBucket
    Value:
      Ref: IMAGEBUCKET
Resources:
  IMAGEBUCKET:
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: AWS::S3::Bucket
  ImageBucketPolicy:
    Properties:
      Bucket:
        Ref: IMAGEBUCKET
      PolicyDocument:
        Statement:
          Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Sub: arn:aws:s3:::${IMAGEBUCKET}/*
    Type: AWS::S3::BucketPolicy
Transform: AWS::Serverless-2016-10-31
