AWSTemplateFormatVersion: 2010-09-09
Outputs:
  OriginRequestFunctionArn:
    Value:
      Fn::GetAtt:
      - OriginRequestFunction
      - Arn
  RoleArn:
    Value:
      Fn::GetAtt:
      - EdgeLambdaRole
      - Arn
  ViewerRequestFunctionArn:
    Value:
      Fn::GetAtt:
      - ViewerRequestFunction
      - Arn
Resources:
  EdgeLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /service-role/
    Type: AWS::IAM::Role
  OriginRequestFunction:
    Properties:
      CodeUri: s3://temp-code-imageresize-244090c246a1bae8/98e3909039fa5b890e54cdadf42564c4
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - EdgeLambdaRole
        - Arn
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
  ViewerRequestFunction:
    Properties:
      CodeUri: s3://temp-code-imageresize-244090c246a1bae8/5448c6a644812eb3e2fdd0eaef53d46f
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - EdgeLambdaRole
        - Arn
      Runtime: nodejs6.10
      Timeout: 1
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
