AWSTemplateFormatVersion: 2010-09-09
Outputs:
  BucketWebsiteUrl:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-BucketWebsiteUrl
    Value:
      Fn::GetAtt:
      - IMAGEBUCKET
      - WebsiteURL
  ImageBucket:
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ImageBucket
    Value:
      Ref: IMAGEBUCKET
  RoleArn:
    Value:
      Fn::GetAtt:
      - EdgeLambdaRole
      - Arn
Resources:
  EdgeLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Type: AWS::IAM::Role
  IMAGEBUCKET:
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    Type: AWS::S3::Bucket
  ImageBucketPolicy:
    Properties:
      Bucket:
        Ref: IMAGEBUCKET
      PolicyDocument:
        Statement:
          Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
            Fn::Sub: arn:aws:s3:::${IMAGEBUCKET}/*
    Type: AWS::S3::BucketPolicy
Transform: AWS::Serverless-2016-10-31
