AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:

  # IMAGEBUCKET:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub "ganeshji-${AWS::Region}${AWS::AccountId}"
  #     AccessControl: PublicRead
  #     WebsiteConfiguration:
  #       IndexDocument: index.html
  ViewerRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "test-${AWS::Region}${AWS::AccountId}-ViewerRequestFunction"
      CodeUri: ../dist/viewer-request-function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 1
#   ImageBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !Ref IMAGEBUCKET
#       PolicyDocument:
#         Statement:
#               Action:
#                 - s3:GetObject
#               Effect: Allow
#               Principal: !GetAtt EdgeLambdaRole.Arn
#               Resource: !Sub arn:aws:s3:::${IMAGEBUCKET}/*
#
#   EdgeLambdaRole:
#     Type: "AWS::IAM::Role"
#     Properties:
#       AssumeRolePolicyDocument:
#         Version: "2012-10-17"
#         Statement:
#             Effect: "Allow"
#             Principal:
#               Service:
#                 - "lambda.amazonaws.com"
#                 - "edgelambda.amazonaws.com"
#             Action:
#               - "sts:AssumeRole"
#       ManagedPolicyArns:
#         - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
#
Outputs:
#   BucketWebsiteUrl:
#     Value: !GetAtt IMAGEBUCKET.WebsiteURL
#     Export:
#       Name: !Sub "${AWS::StackName}-BucketWebsiteUrl"

  ViewerRequestFunctionArn:
     Value: !GetAtt ViewerRequestFunction.Arn
